// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-a_y9YUPo-a2vo5eI0v8NncG38kRHqbY',
    appId: '1:28963892545:web:0789a35fef79276f18c5c0',
    messagingSenderId: '28963892545',
    projectId: 'elservices-48d1e',
    authDomain: 'elservices-48d1e.firebaseapp.com',
    databaseURL: 'https://elservices-48d1e-default-rtdb.firebaseio.com',
    storageBucket: 'elservices-48d1e.appspot.com',
    measurementId: 'G-BKD7V0M8TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9l14D72ZsFGndsTNWxYX2G8GeJ6923Y',
    appId: '1:28963892545:android:858ab1706de78b6118c5c0',
    messagingSenderId: '28963892545',
    projectId: 'elservices-48d1e',
    databaseURL: 'https://elservices-48d1e-default-rtdb.firebaseio.com',
    storageBucket: 'elservices-48d1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUMUtypWH1iCf0wjjKmcjK2FnjwKM4JTE',
    appId: '1:28963892545:ios:0c9cc4de6026efb218c5c0',
    messagingSenderId: '28963892545',
    projectId: 'elservices-48d1e',
    databaseURL: 'https://elservices-48d1e-default-rtdb.firebaseio.com',
    storageBucket: 'elservices-48d1e.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUMUtypWH1iCf0wjjKmcjK2FnjwKM4JTE',
    appId: '1:28963892545:ios:0c9cc4de6026efb218c5c0',
    messagingSenderId: '28963892545',
    projectId: 'elservices-48d1e',
    databaseURL: 'https://elservices-48d1e-default-rtdb.firebaseio.com',
    storageBucket: 'elservices-48d1e.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-a_y9YUPo-a2vo5eI0v8NncG38kRHqbY',
    appId: '1:28963892545:web:72eb357b485e791a18c5c0',
    messagingSenderId: '28963892545',
    projectId: 'elservices-48d1e',
    authDomain: 'elservices-48d1e.firebaseapp.com',
    databaseURL: 'https://elservices-48d1e-default-rtdb.firebaseio.com',
    storageBucket: 'elservices-48d1e.appspot.com',
    measurementId: 'G-BVH4W81G46',
  );

}